#!/usr/bin/env python3
# Run this script:
# $ ./scripts/generate_maintainers.py

from utils import github_page_for_contributor
from utils.contributors import CONTRIBUTORS_FILE, parse_contributors_file

template = """
<!--
This file is automatically generated. To add yourself or to change
your information, you need to change {CONTRIBUTORS_FILE}
-->
# Maintainers

{maintainers}
"""


def format_maintainer(maintainer):
    display_name = maintainer['displayName']
    formatted_name = display_name
    extra = maintainer.get('extra')
    if extra is not None:
        formatted_name += extra
    bio = maintainer.get('bio', '')

    return f'### {formatted_name}\n\n{bio}'


if __name__ == '__main__':
    contributors_data = parse_contributors_file()

    maintainers = filter(lambda c: c.get('maintainer')
                         == True, contributors_data)

    output = template.format(
        maintainers='\n'.join((format_maintainer(m) for m in maintainers)),
        CONTRIBUTORS_FILE=CONTRIBUTORS_FILE
    )

    with open('MAINTAINERS.md', 'w') as output_file:
        output_file.write(output)
