#!/usr/bin/env python3
# Run this script:
# $ ./scripts/generate_contributors.py

import subprocess
from utils import github_page_for_contributor
from utils.contributors import CONTRIBUTORS_FILE, parse_contributors_file, sorted_authors_from_raw_shortlog_lines


template = """
<!--
This file is automatically generated. To add yourself or to change
your information, you need to change {CONTRIBUTORS_FILE}
-->
## Contributors

We are grateful to the following people for their contributions to
the library.

{names}

If you contributed to the library and don't see yourself on this list,
read the instructions on
[adding yourself as a contributor](CONTRIBUTING.md#add-contributor).

Help us to improve the library by contributing to the project!
Contributions come in many forms, please ask us if you are not sure
how to help. We are happy to help you get started.
"""


def format_contributor(contributor):
    display_name = contributor['displayName']
    github_page = github_page_for_contributor(contributor)
    if github_page:
        return f'- [{display_name}]({github_page})'
    return f'- {display_name}'


if __name__ == '__main__':
    contributors_data = parse_contributors_file()

    git_log_output = subprocess.run([
        'git', 'shortlog',
        '-ns',
        '--invert-grep', '--grep=^chore:',
        '--group=author', '--group=trailer:co-authored-by',
        'HEAD'
    ], capture_output=True, text=True, check=True).stdout.splitlines()

    sorted_authors = sorted_authors_from_raw_shortlog_lines(
        git_log_output, contributors_data)
    output = template.format(
        names='\n'.join((format_contributor(c) for c in sorted_authors)),
        CONTRIBUTORS_FILE=CONTRIBUTORS_FILE
    )

    with open('CONTRIBUTORS.md', 'w') as output_file:
        output_file.write(output)
